apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: github-tekon-quay-nodejs-14
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-tekon-quay-nodejs-14 
  name: github-tekon-quay-nodejs-14
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: github-tekon-quay-nodejs-14 
